DROP ROLE IF EXISTS sword_explorer;
CREATE ROLE "sword_explorer" WITH
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  INHERIT
  NOREPLICATION
  CONNECTION LIMIT -1
  PASSWORD '4$wbX*cbC-GxC2i';

ALTER ROLE sword_explorer WITH LOGIN ;

drop schema IF EXISTS sword_data CASCADE ;

CREATE SCHEMA IF NOT EXISTS sword_data AUTHORIZATION sword_explorer;

set search_path = "sword_data";

--
-- -- Database: SwordExplorer
-- CREATE DATABASE SwordNotes
--   WITH
--   OWNER = sword_explorer
--   ENCODING = 'UTF8'
--   LC_COLLATE = 'en_US.UTF-8'
--   LC_CTYPE = 'en_US.UTF-8'
--   TABLESPACE = pg_default
--   CONNECTION LIMIT = -1;
--
-- ALTER DEFAULT PRIVILEGES
--   GRANT ALL ON TABLES TO lcollins2;
--
-- ALTER DEFAULT PRIVILEGES
--   GRANT ALL ON TABLES TO "sword_explorer";

----------------------------------------- Table: public.role -----------------------------------------
CREATE TABLE public.role
(
  id   bigint generated by default as identity NOT NULL,
  name character varying(255) COLLATE pg_catalog."default",
  CONSTRAINT role_pk PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE public.role
  OWNER to sword_explorer;

----------------------------------------- Table: public.notes_user -----------------------------------------
CREATE TABLE public.notes_user
(
  id       bigint NOT NULL,
  name     character varying(255) COLLATE pg_catalog."default",
  password character varying(255) COLLATE pg_catalog."default",
  username character varying(100) UNIQUE,
  CONSTRAINT notes_user_pk PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE public.notes_user
  OWNER to sword_explorer;

----------------------------------------- Table: public.notes_user_roles -----------------------------------------
CREATE TABLE public.notes_user_roles
(
  notes_user_id bigint NOT NULL,
  roles_id      bigint NOT NULL,
  CONSTRAINT notes_user_roles_fk_notes_user FOREIGN KEY (notes_user_id)
    REFERENCES public.notes_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT notes_user_roles_fk_roles FOREIGN KEY (roles_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)
  TABLESPACE pg_default;

ALTER TABLE public.notes_user_roles
  OWNER to sword_explorer;

----------------------------------------- Table: public.note -----------------------------------------

--- sword_explorer
--- 4$wbX*cbC-GxC2i
CREATE TABLE public.note
(
  id         bigint generated by default as identity NOT NULL,
  comments   character varying(255) COLLATE pg_catalog."default",
  verse_spec character varying(255) COLLATE pg_catalog."default",
  CONSTRAINT note_pkey PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE public.note
  OWNER to sword_explorer;

----------------------------------------- Table: public.bible_topic -----------------------------------------
create table public.bible_topic
(
  id       int generated by default as identity,
  title    varchar(255),
  username varchar(255),
  CONSTRAINT bible_topic_pkey PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE public.bible_topic
  OWNER to sword_explorer;

----------------------------------------- Table: public.bible_topic_notes -----------------------------------------
CREATE TABLE public.bible_topic_notes
(
  bible_topic_id bigint NOT NULL,
  notes_id       bigint NOT NULL,
  CONSTRAINT bible_topic_notes_uniq UNIQUE (notes_id),
  CONSTRAINT bible_topic_notes_fk_notes FOREIGN KEY (notes_id)
    REFERENCES public.note (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT bible_topic_notes_fk_bible_topic FOREIGN KEY (bible_topic_id)
    REFERENCES public.bible_topic (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)
  TABLESPACE pg_default;

ALTER TABLE public.bible_topic_notes
  OWNER to sword_explorer;

----------------------------------------- Grant Permissions -----------------------------------------


GRANT ALL ON TABLE public.bible_topic TO "sword_explorer";

GRANT ALL ON TABLE public.bible_topic_notes TO "sword_explorer";

GRANT ALL ON TABLE public.note TO "sword_explorer";

GRANT ALL ON TABLE public.notes_user_roles TO "sword_explorer";

GRANT ALL ON TABLE public.notes_user TO "sword_explorer";

-- H!F4d5evxv$f
