------------------------------------ Table: public.role -----------------------------------------
CREATE TABLE sword_data.role
(
  id   bigint generated by default as identity NOT NULL,
  name character varying(255) COLLATE pg_catalog."default" UNIQUE,
  CONSTRAINT role_pk PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.role
  OWNER to sword_explorer;

----------------------------------------- Table: public.notes_user -----------------------------------------
CREATE TABLE sword_data.notes_user
(
  id       bigint NOT NULL,
  name     character varying(255) COLLATE pg_catalog."default",
  password character varying(255) COLLATE pg_catalog."default",
  username character varying(100) UNIQUE,
  CONSTRAINT notes_user_pk PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.notes_user
  OWNER to sword_explorer;

----------------------------------------- Table: public.notes_user_roles -----------------------------------------
CREATE TABLE sword_data.notes_user_roles
(
  notes_user_id bigint NOT NULL,
  roles_id      bigint NOT NULL,
  CONSTRAINT notes_user_roles_fk_notes_user FOREIGN KEY (notes_user_id)
    REFERENCES sword_data.notes_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT notes_user_roles_fk_roles FOREIGN KEY (roles_id)
    REFERENCES sword_data.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.notes_user_roles
  OWNER to sword_explorer;

----------------------------------------- Table: public.note -----------------------------------------
--- sword_explorer
--- 4$wbX*cbC-GxC2i
CREATE TABLE sword_data.note
(
  id         bigint generated by default as identity NOT NULL,
  comments   character varying(255) COLLATE pg_catalog."default",
  verse_spec character varying(255) COLLATE pg_catalog."default",
  is_bible_verse boolean DEFAULT (true),
  CONSTRAINT note_pkey PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.note
  OWNER to sword_explorer;

----------------------------------------- Table: public.bible_topic -----------------------------------------
DROP TABLE IF EXISTS sword_data.bible_topic CASCADE ;

create table sword_data.bible_topic
(
  id       int generated by default as identity,
  title    varchar(255),
  author varchar(100),
  username varchar(50),
  created_at date NOT NULL,
  CONSTRAINT bible_topic_pkey PRIMARY KEY (id)
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.bible_topic
  OWNER to sword_explorer;

----------------------------------------- Table: public.bible_topic_notes -----------------------------------------
CREATE TABLE sword_data.bible_topic_notes
(
  bible_topic_id bigint NOT NULL,
  notes_id       bigint NOT NULL,
  CONSTRAINT bible_topic_notes_uniq UNIQUE (notes_id),
  CONSTRAINT bible_topic_notes_fk_notes FOREIGN KEY (notes_id)
    REFERENCES sword_data.note (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
  CONSTRAINT bible_topic_notes_fk_bible_topic FOREIGN KEY (bible_topic_id)
    REFERENCES sword_data.bible_topic (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)
  TABLESPACE pg_default;

ALTER TABLE sword_data.bible_topic_notes
  OWNER to sword_explorer;

----------------------------------------- Grant Permissions -----------------------------------------

GRANT ALL ON TABLE sword_data.bible_topic TO "sword_explorer";

GRANT ALL ON TABLE sword_data.bible_topic_notes TO "sword_explorer";

GRANT ALL ON TABLE sword_data.note TO "sword_explorer";

GRANT ALL ON TABLE sword_data.notes_user_roles TO "sword_explorer";

GRANT ALL ON TABLE sword_data.notes_user TO "sword_explorer";

-- H!F4d5evxv$f
